### PR TITLE
fix(aepp): use networkId in rpc tx signing

### LINKED ISSUE #1559: Examples Aepp(SDK v12) is not working with web wallet extension(SDK v11)
examples/browser/aepp SDK version: 12
web wallet extension SDK version: 11

Building ✅(building with minor changes)
Wallet connection ✅
Contract compile ✅
Spend/Contract deploy ❌

```
schema.ts?ea10:60 Uncaught (in promise) InternalError: Can't find RpcError with code: 8
    at RpcError.deserialize (schema.ts?ea10:60:1)
    at RpcClient._processResponse2 (RpcClient.ts?c13a:176:1)
    at RpcClient._handleMessage2 (RpcClient.ts?c13a:118:1)
    at listener (BrowserWindowMessage.ts?ce91:102:1)
```

### PR DESCRIPTION
**Pull request by subhod-i**
networkId is marked deprecated but using now to make SDK v12 aepps compatible with wallets using v11.0.1 and below.
Closes #1559

### CODE REVIEW

File: src/account/rpc.ts [hunk 1]
```diff
@@ -3,6 +3,16 @@ import { METHODS } from '../utils/aepp-wallet-communication/schema'
 import { NotImplementedError } from '../utils/errors'
 import { EncodedData } from '../utils/encoder'
 
+// TODO: Remove networkId and use type Parameters<AccountBase['signTransaction']>[1]
+// networkId required to maintain backward compatablity with wallets using SDK v11.0.1 and below
+type RpcSignTransaction = Parameters<AccountBase['signTransaction']>[1] & {
```
Comment (davidyuk) [inline src/account/rpc.ts:8]: `signTransaction` already accepts `networkId` and I'm not planning to change it, so this type is not necessary

**Review by davidyuk — APPROVED** [review]

File: src/account/rpc.ts (hunk 1 above)
Comment (subhod-i) [reply src/account/rpc.ts]: I added the tag `deprecated` to the RpcSignTransaction  filed `networkId` to inform the developers. The main `signTransaction` still accepts the `networkId` but we have removed it from the RPC call. I believe it is important to mark the field `networkId` as deprecated

Comment (subhod-i) [reply src/account/rpc.ts]: Oh, I see, You have marked it deprecated another way. I hope that raises a warning while developers trying to use the field.
